# Generated by Django 5.1.3 on 2024-11-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoice',
            table='invoice',
        ),
        migrations.AlterModelTable(
            name='invoicedetail',
            table='invoice_detail',
        ),
    ]
